compilers:
  - compiler:
      environment: {}
      extra_rpaths: []
      # Axom example sidre_shocktube_F_ex doesn't link otherwise
      flags:
        cflags: -fPIC -pthread
        cxxflags: -fPIC -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: clang@10.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/gcc-8
        cxx: /usr/bin/g++-8
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: gcc@8.4.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/gcc-9
        cxx: /usr/bin/g++-9
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: gcc@9.3.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/gcc-11
        cxx: /usr/bin/g++-11
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: gcc@11.1.0
      target: x86_64
