spack:
  compilers::
  - compiler:
      spec: gcc@8.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: 
        ldlibs: -lpthread
      operating_system: ubuntu18.04
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []

  # Regular TPLs do not need views
  view: false

  packages:
    all:
      compiler: [gcc]
      providers:
        mpi: [mpich]
        blas: [openblas]
        lapack: [openblas]
        gl: [opengl]
        glu: [openglu]

    # Lock down which MPI we are using
    mpi:
      buildable: false
    mpich:
      externals:
      - spec: mpich@3.3a2%gcc@8.4.0
        prefix: /usr

  # Lock down versions of packages we depend on
    opengl:
      buildable: false
      externals:
      - spec: opengl@1.0.0
        prefix: /usr
    openglu:
      buildable: false
      externals:
      - spec: openglu@1.3.1
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.26.1
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.29
        prefix: /
    libx11:
      buildable: false
      externals:
      - spec: libx11@1.6.4
        prefix: /usr
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    openssl:
      externals:
      - spec: openssl@1.1.1
        prefix: /usr/lib/x86_64-linux-gnu/
    openblas:
      buildable: false
      externals:
      - spec: openblas@0.2.20
        prefix: /usr/lib/x86_64-linux-gnu/

    # Lock in versions of Devtools
    cmake:
      buildable: false
      externals:
      - spec: cmake@3.20.1
        prefix: /usr
    cppcheck:
      version: [1.82]
      buildable: false
      externals:
      - spec: cppcheck@1.82
        prefix: /usr
    doxygen:
      version: [1.8.13]
      buildable: false
      externals:
      - spec: doxygen@1.8.13
        prefix: /usr
    llvm:
      version: [10.0.0]
      buildable: false
      externals:
      - spec: llvm@10.0.0+clang
        prefix: /usr
    python:
      version: [3.7.5]
      buildable: false
      externals:
      - spec: python@3.7.5
        prefix: /usr
    py-sphinx:
      version: [1.6.7]
      buildable: false
      externals:
      - spec: py-sphinx@1.6.7
        prefix: /usr
