
# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    # This defaults us to machine specific flags of ivybridge which allows
    # us to run on broadwell as well
    target: [ivybridge]
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      lapack: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [mpich]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
# Spack may grab for mpi & we don't want to use them
  charm:
    buildable: False
  mpilander:
    buildable: False  
# System level packages to not build
  autotools:
    paths:
      autotools: /usr/bin/
    buildable: False 
  bzip2:
   paths:
      bzip2: /usr/bin/
   buildable: False
  gettext:
   paths:
      gettext: /usr/bin/
   buildable: False
  m4:
   paths:
      m4: /usr/bin/
   buildable: False
  pkg-config:
    paths:
      pkg-config: /usr/bin/
    buildable: False 
  tar:
   paths:
      tar: /usr/bin/
   buildable: False
  graphviz:
    paths:
      graphviz: /usr/bin/
    buildable: False
  openblas:
    paths:
      openblas: /usr
    buildable: False
# Globally lock in version of CMake
  cmake:
    version: [3.10.1]
  mfem:
    version: [4.0.0]
  hypre:
    version: [2.11.1]
  superlu-dist:
    version: [5.4.0]
  parmetis:
    version: [4.0.3]
  metis:
    version: [5.1.0]
