# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [netlib-lapack]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [netlib-lapack]
      mkl: [intel-mkl]
      mpe: [mpe2]
      # IBM Spectrum MPI is the only supported MPI 
      # library on LC's Sierra and CORAL EA systems.
      mpi: [spectrum-mpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
  conduit:
    version: [master]
  python:
    variants: ~dbm
  py-numpy:
    variants: ~blas~lapack
  perl:
    buildable: false
    externals:
    - spec: perl@5.16.3
      prefix: /usr
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr

  # LLNL blueos CUDA
  cuda:
    externals:
      - spec: cuda@11.2.0
        prefix: /usr/tce/packages/cuda/cuda-11.2.0
    buildable: false

  # LLNL blueos mpi
  mpi:
    buildable: false
  spectrum-mpi:
    externals:
      - spec: spectrum-mpi@release%clang@10.0.1
        prefix: /usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-clang-10.0.1-gcc-8.3.1

  # System level packages to not build
  autoconf:
    externals:
      - spec: autoconf@2.69
        prefix: /usr
    buildable: false 
  automake:
    externals:
      - spec: automake@1.13.4
        prefix: /usr
    buildable: false
  bzip2:
    externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    buildable: false
  gettext:
    externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    buildable: false
  libtool:
    externals:
      - spec: libtool@2.4.2
        prefix: /usr
    buildable: false
  m4:
    externals:
      - spec: m4@1.4.16
        prefix: /usr
    buildable: false
  tar:
    externals:
      - spec: tar@1.26
        prefix: /usr
    buildable: false
  netlib-lapack:
    externals:
      # This is the one that has the trailing underscores in name mangling, needed for MFEM compat
      - spec: netlib-lapack@3.9.0
        prefix: /usr/tcetmp/packages/lapack/lapack-3.9.0-gcc-7.3.1/lib/
    buildable: false

  # Lock in versions of Devtools
  cmake:
    externals:
    - spec: cmake@3.18.0
      prefix: /usr/tce/packages/cmake/cmake-3.18.0
    buildable: false
  cppcheck:
    version: [2.1]
    externals:
      - spec: cppcheck@2.1
        prefix: /usr/WS2/smithdev/devtools/blueos_3_ppc64le_ib_p9/latest/cppcheck-2.1
    buildable: false
  doxygen:
    version: [1.8.17]
    externals:
      - spec: doxygen@1.8.17
        prefix: /usr/WS2/smithdev/devtools/blueos_3_ppc64le_ib_p9/latest/doxygen-1.8.17
    buildable: false
  llvm:
    version: [10.0.0]
    buildable: false
    externals:
    - spec: llvm+clang@10.0.0
      prefix: /usr/tce/packages/clang/clang-10.0.0
  python:
    version: [3.8.2]
    externals:
      - spec: python@3.8.2
        prefix: /usr/tce/packages/python/python-3.8.2/
    buildable: false
  py-sphinx:
    version: [2.2.0]
    externals:
      - spec: py-sphinx@2.2.0
        prefix: /usr/tce/packages/python/python-3.8.2/
    buildable: false
